<?xml version="1.0" encoding="utf-8"?><Database Name="Natsu" Class="DataNatsuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.10.248;Initial Catalog=Natsu;Persist Security Info=True;User ID=sa" SettingsObjectName="Natsu.Properties.Settings" SettingsPropertyName="NatsuConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_MissImageCheck" Member="tbl_MissImageChecks">
    <Type Name="tbl_MissImageCheck">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdImage" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserNameCheck" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SubmitCheck" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Batch" Member="tbl_Batches">
    <Type Name="tbl_Batch">
      <Column Name="IDBatch" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fdatecreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fusercreate" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="fPathPicture" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="fMultiEntry" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="fLocation" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="fGhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_DESo" Member="tbl_DESos">
    <Type Name="tbl_DESo">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdImage" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdPhieu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TruongSo01" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo02" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo03" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo04" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo05" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo06" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo07" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo08" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo09" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo10" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo11" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo12" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo13" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo14" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo15" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo16" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo17" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo18" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo19" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo20" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo21" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo22" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo23" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo24" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Dem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Error" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="True" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateInput" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_DESo_BackUp" Member="tbl_DESo_BackUps">
    <Type Name="tbl_DESo_BackUp">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdImage" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdPhieu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TruongSo01" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo02" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo03" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo04" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo05" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo06" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo07" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo08" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo09" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo10" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo11" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo12" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo13" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo14" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo15" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo16" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo17" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo18" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo19" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo20" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo21" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo22" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo23" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TruongSo24" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Dem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Error" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="True" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateInput" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Image" Member="tbl_Images">
    <Type Name="tbl_Image">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdImage" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserNameDESo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ReadImageDESo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CheckedDESo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TienDoDESO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_LogFile" Member="tbl_LogFiles">
    <Type Name="tbl_LogFile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Info" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="DateLog" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MissImage" Member="tbl_MissImages">
    <Type Name="tbl_MissImage">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdImage" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserNameDESo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SubmitDESo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>