#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natsu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Natsu")]
	public partial class DataNatsuDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Batch(tbl_Batch instance);
    partial void Updatetbl_Batch(tbl_Batch instance);
    partial void Deletetbl_Batch(tbl_Batch instance);
    partial void Inserttbl_MissImage_DESO(tbl_MissImage_DESO instance);
    partial void Updatetbl_MissImage_DESO(tbl_MissImage_DESO instance);
    partial void Deletetbl_MissImage_DESO(tbl_MissImage_DESO instance);
    partial void Inserttbl_DESO(tbl_DESO instance);
    partial void Updatetbl_DESO(tbl_DESO instance);
    partial void Deletetbl_DESO(tbl_DESO instance);
    partial void Inserttbl_DESO_Backup(tbl_DESO_Backup instance);
    partial void Updatetbl_DESO_Backup(tbl_DESO_Backup instance);
    partial void Deletetbl_DESO_Backup(tbl_DESO_Backup instance);
    partial void Inserttbl_Image(tbl_Image instance);
    partial void Updatetbl_Image(tbl_Image instance);
    partial void Deletetbl_Image(tbl_Image instance);
    partial void Inserttbl_MissCheck_DESO(tbl_MissCheck_DESO instance);
    partial void Updatetbl_MissCheck_DESO(tbl_MissCheck_DESO instance);
    partial void Deletetbl_MissCheck_DESO(tbl_MissCheck_DESO instance);
    #endregion
		
		public DataNatsuDataContext() : 
				base(global::Natsu.Properties.Settings.Default.NatsuConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataNatsuDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataNatsuDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataNatsuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataNatsuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Batch> tbl_Batches
		{
			get
			{
				return this.GetTable<tbl_Batch>();
			}
		}
		
		public System.Data.Linq.Table<tbl_MissImage_DESO> tbl_MissImage_DESOs
		{
			get
			{
				return this.GetTable<tbl_MissImage_DESO>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DESO> tbl_DESOs
		{
			get
			{
				return this.GetTable<tbl_DESO>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DESO_Backup> tbl_DESO_Backups
		{
			get
			{
				return this.GetTable<tbl_DESO_Backup>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Image> tbl_Images
		{
			get
			{
				return this.GetTable<tbl_Image>();
			}
		}
		
		public System.Data.Linq.Table<tbl_MissCheck_DESO> tbl_MissCheck_DESOs
		{
			get
			{
				return this.GetTable<tbl_MissCheck_DESO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Batch")]
	public partial class tbl_Batch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDBatch;
		
		private string _fBatchName;
		
		private System.Nullable<System.DateTime> _fdatecreated;
		
		private string _fusercreate;
		
		private string _fPathPicture;
		
		private string _fLocation;
		
		private string _fSoLuongAnh;
		
		private string _LoaiBatch;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBatchChanging(long value);
    partial void OnIDBatchChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnfdatecreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnfdatecreatedChanged();
    partial void OnfusercreateChanging(string value);
    partial void OnfusercreateChanged();
    partial void OnfPathPictureChanging(string value);
    partial void OnfPathPictureChanged();
    partial void OnfLocationChanging(string value);
    partial void OnfLocationChanged();
    partial void OnfSoLuongAnhChanging(string value);
    partial void OnfSoLuongAnhChanged();
    partial void OnLoaiBatchChanging(string value);
    partial void OnLoaiBatchChanged();
    #endregion
		
		public tbl_Batch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBatch", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDBatch
		{
			get
			{
				return this._IDBatch;
			}
			set
			{
				if ((this._IDBatch != value))
				{
					this.OnIDBatchChanging(value);
					this.SendPropertyChanging();
					this._IDBatch = value;
					this.SendPropertyChanged("IDBatch");
					this.OnIDBatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fdatecreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> fdatecreated
		{
			get
			{
				return this._fdatecreated;
			}
			set
			{
				if ((this._fdatecreated != value))
				{
					this.OnfdatecreatedChanging(value);
					this.SendPropertyChanging();
					this._fdatecreated = value;
					this.SendPropertyChanged("fdatecreated");
					this.OnfdatecreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fusercreate", DbType="NVarChar(200)")]
		public string fusercreate
		{
			get
			{
				return this._fusercreate;
			}
			set
			{
				if ((this._fusercreate != value))
				{
					this.OnfusercreateChanging(value);
					this.SendPropertyChanging();
					this._fusercreate = value;
					this.SendPropertyChanged("fusercreate");
					this.OnfusercreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPathPicture", DbType="NVarChar(200)")]
		public string fPathPicture
		{
			get
			{
				return this._fPathPicture;
			}
			set
			{
				if ((this._fPathPicture != value))
				{
					this.OnfPathPictureChanging(value);
					this.SendPropertyChanging();
					this._fPathPicture = value;
					this.SendPropertyChanged("fPathPicture");
					this.OnfPathPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fLocation", DbType="NVarChar(200)")]
		public string fLocation
		{
			get
			{
				return this._fLocation;
			}
			set
			{
				if ((this._fLocation != value))
				{
					this.OnfLocationChanging(value);
					this.SendPropertyChanging();
					this._fLocation = value;
					this.SendPropertyChanged("fLocation");
					this.OnfLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fSoLuongAnh", DbType="NVarChar(200)")]
		public string fSoLuongAnh
		{
			get
			{
				return this._fSoLuongAnh;
			}
			set
			{
				if ((this._fSoLuongAnh != value))
				{
					this.OnfSoLuongAnhChanging(value);
					this.SendPropertyChanging();
					this._fSoLuongAnh = value;
					this.SendPropertyChanged("fSoLuongAnh");
					this.OnfSoLuongAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiBatch", DbType="NVarChar(200)")]
		public string LoaiBatch
		{
			get
			{
				return this._LoaiBatch;
			}
			set
			{
				if ((this._LoaiBatch != value))
				{
					this.OnLoaiBatchChanging(value);
					this.SendPropertyChanging();
					this._LoaiBatch = value;
					this.SendPropertyChanged("LoaiBatch");
					this.OnLoaiBatchChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_MissImage_DESO")]
	public partial class tbl_MissImage_DESO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private System.Nullable<int> _Submit;
		
		private System.Nullable<System.DateTime> _DateInput;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnSubmitChanging(System.Nullable<int> value);
    partial void OnSubmitChanged();
    partial void OnDateInputChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInputChanged();
    #endregion
		
		public tbl_MissImage_DESO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Submit", DbType="Int")]
		public System.Nullable<int> Submit
		{
			get
			{
				return this._Submit;
			}
			set
			{
				if ((this._Submit != value))
				{
					this.OnSubmitChanging(value);
					this.SendPropertyChanging();
					this._Submit = value;
					this.SendPropertyChanged("Submit");
					this.OnSubmitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInput", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateInput
		{
			get
			{
				return this._DateInput;
			}
			set
			{
				if ((this._DateInput != value))
				{
					this.OnDateInputChanging(value);
					this.SendPropertyChanging();
					this._DateInput = value;
					this.SendPropertyChanged("DateInput");
					this.OnDateInputChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DESO")]
	public partial class tbl_DESO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private string _Truong_01;
		
		private string _Truong_02;
		
		private string _Truong_03;
		
		private string _Truong_04;
		
		private string _Truong_05;
		
		private string _Truong_06;
		
		private string _Truong_07;
		
		private string _Truong_08;
		
		private string _Truong_09;
		
		private string _Truong_10;
		
		private int _IdPhieu;
		
		private System.Nullable<int> _Dem;
		
		private System.Nullable<int> _Error;
		
		private System.Nullable<int> _True;
		
		private System.Nullable<System.DateTime> _DateInput;
		
		private string _STT;
		
		private string _Date;
		
		private string _LoaiBatch;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnTruong_01Changing(string value);
    partial void OnTruong_01Changed();
    partial void OnTruong_02Changing(string value);
    partial void OnTruong_02Changed();
    partial void OnTruong_03Changing(string value);
    partial void OnTruong_03Changed();
    partial void OnTruong_04Changing(string value);
    partial void OnTruong_04Changed();
    partial void OnTruong_05Changing(string value);
    partial void OnTruong_05Changed();
    partial void OnTruong_06Changing(string value);
    partial void OnTruong_06Changed();
    partial void OnTruong_07Changing(string value);
    partial void OnTruong_07Changed();
    partial void OnTruong_08Changing(string value);
    partial void OnTruong_08Changed();
    partial void OnTruong_09Changing(string value);
    partial void OnTruong_09Changed();
    partial void OnTruong_10Changing(string value);
    partial void OnTruong_10Changed();
    partial void OnIdPhieuChanging(int value);
    partial void OnIdPhieuChanged();
    partial void OnDemChanging(System.Nullable<int> value);
    partial void OnDemChanged();
    partial void OnErrorChanging(System.Nullable<int> value);
    partial void OnErrorChanged();
    partial void OnTrueChanging(System.Nullable<int> value);
    partial void OnTrueChanged();
    partial void OnDateInputChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInputChanged();
    partial void OnSTTChanging(string value);
    partial void OnSTTChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnLoaiBatchChanging(string value);
    partial void OnLoaiBatchChanged();
    #endregion
		
		public tbl_DESO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_01", DbType="NVarChar(255)")]
		public string Truong_01
		{
			get
			{
				return this._Truong_01;
			}
			set
			{
				if ((this._Truong_01 != value))
				{
					this.OnTruong_01Changing(value);
					this.SendPropertyChanging();
					this._Truong_01 = value;
					this.SendPropertyChanged("Truong_01");
					this.OnTruong_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_02", DbType="NVarChar(255)")]
		public string Truong_02
		{
			get
			{
				return this._Truong_02;
			}
			set
			{
				if ((this._Truong_02 != value))
				{
					this.OnTruong_02Changing(value);
					this.SendPropertyChanging();
					this._Truong_02 = value;
					this.SendPropertyChanged("Truong_02");
					this.OnTruong_02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_03", DbType="NVarChar(255)")]
		public string Truong_03
		{
			get
			{
				return this._Truong_03;
			}
			set
			{
				if ((this._Truong_03 != value))
				{
					this.OnTruong_03Changing(value);
					this.SendPropertyChanging();
					this._Truong_03 = value;
					this.SendPropertyChanged("Truong_03");
					this.OnTruong_03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_04", DbType="NVarChar(255)")]
		public string Truong_04
		{
			get
			{
				return this._Truong_04;
			}
			set
			{
				if ((this._Truong_04 != value))
				{
					this.OnTruong_04Changing(value);
					this.SendPropertyChanging();
					this._Truong_04 = value;
					this.SendPropertyChanged("Truong_04");
					this.OnTruong_04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_05", DbType="NVarChar(255)")]
		public string Truong_05
		{
			get
			{
				return this._Truong_05;
			}
			set
			{
				if ((this._Truong_05 != value))
				{
					this.OnTruong_05Changing(value);
					this.SendPropertyChanging();
					this._Truong_05 = value;
					this.SendPropertyChanged("Truong_05");
					this.OnTruong_05Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_06", DbType="NVarChar(255)")]
		public string Truong_06
		{
			get
			{
				return this._Truong_06;
			}
			set
			{
				if ((this._Truong_06 != value))
				{
					this.OnTruong_06Changing(value);
					this.SendPropertyChanging();
					this._Truong_06 = value;
					this.SendPropertyChanged("Truong_06");
					this.OnTruong_06Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_07", DbType="NVarChar(255)")]
		public string Truong_07
		{
			get
			{
				return this._Truong_07;
			}
			set
			{
				if ((this._Truong_07 != value))
				{
					this.OnTruong_07Changing(value);
					this.SendPropertyChanging();
					this._Truong_07 = value;
					this.SendPropertyChanged("Truong_07");
					this.OnTruong_07Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_08", DbType="NVarChar(255)")]
		public string Truong_08
		{
			get
			{
				return this._Truong_08;
			}
			set
			{
				if ((this._Truong_08 != value))
				{
					this.OnTruong_08Changing(value);
					this.SendPropertyChanging();
					this._Truong_08 = value;
					this.SendPropertyChanged("Truong_08");
					this.OnTruong_08Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_09", DbType="NVarChar(255)")]
		public string Truong_09
		{
			get
			{
				return this._Truong_09;
			}
			set
			{
				if ((this._Truong_09 != value))
				{
					this.OnTruong_09Changing(value);
					this.SendPropertyChanging();
					this._Truong_09 = value;
					this.SendPropertyChanged("Truong_09");
					this.OnTruong_09Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_10", DbType="NVarChar(255)")]
		public string Truong_10
		{
			get
			{
				return this._Truong_10;
			}
			set
			{
				if ((this._Truong_10 != value))
				{
					this.OnTruong_10Changing(value);
					this.SendPropertyChanging();
					this._Truong_10 = value;
					this.SendPropertyChanged("Truong_10");
					this.OnTruong_10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPhieu
		{
			get
			{
				return this._IdPhieu;
			}
			set
			{
				if ((this._IdPhieu != value))
				{
					this.OnIdPhieuChanging(value);
					this.SendPropertyChanging();
					this._IdPhieu = value;
					this.SendPropertyChanged("IdPhieu");
					this.OnIdPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dem", DbType="Int")]
		public System.Nullable<int> Dem
		{
			get
			{
				return this._Dem;
			}
			set
			{
				if ((this._Dem != value))
				{
					this.OnDemChanging(value);
					this.SendPropertyChanging();
					this._Dem = value;
					this.SendPropertyChanged("Dem");
					this.OnDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Int")]
		public System.Nullable<int> Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_True", DbType="Int")]
		public System.Nullable<int> True
		{
			get
			{
				return this._True;
			}
			set
			{
				if ((this._True != value))
				{
					this.OnTrueChanging(value);
					this.SendPropertyChanging();
					this._True = value;
					this.SendPropertyChanged("True");
					this.OnTrueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInput", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateInput
		{
			get
			{
				return this._DateInput;
			}
			set
			{
				if ((this._DateInput != value))
				{
					this.OnDateInputChanging(value);
					this.SendPropertyChanging();
					this._DateInput = value;
					this.SendPropertyChanged("DateInput");
					this.OnDateInputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="NVarChar(100)")]
		public string STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="NVarChar(255)")]
		public string Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiBatch", DbType="NVarChar(50)")]
		public string LoaiBatch
		{
			get
			{
				return this._LoaiBatch;
			}
			set
			{
				if ((this._LoaiBatch != value))
				{
					this.OnLoaiBatchChanging(value);
					this.SendPropertyChanging();
					this._LoaiBatch = value;
					this.SendPropertyChanged("LoaiBatch");
					this.OnLoaiBatchChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DESO_Backup")]
	public partial class tbl_DESO_Backup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private string _Truong_01;
		
		private string _Truong_02;
		
		private string _Truong_03;
		
		private string _Truong_04;
		
		private string _Truong_05;
		
		private string _Truong_06;
		
		private string _Truong_07;
		
		private string _Truong_08;
		
		private string _Truong_09;
		
		private string _Truong_10;
		
		private int _IdPhieu;
		
		private System.Nullable<int> _Dem;
		
		private System.Nullable<int> _Error;
		
		private System.Nullable<int> _True;
		
		private System.Nullable<System.DateTime> _DateInput;
		
		private string _STT;
		
		private string _Date;
		
		private string _LoaiBatch;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnTruong_01Changing(string value);
    partial void OnTruong_01Changed();
    partial void OnTruong_02Changing(string value);
    partial void OnTruong_02Changed();
    partial void OnTruong_03Changing(string value);
    partial void OnTruong_03Changed();
    partial void OnTruong_04Changing(string value);
    partial void OnTruong_04Changed();
    partial void OnTruong_05Changing(string value);
    partial void OnTruong_05Changed();
    partial void OnTruong_06Changing(string value);
    partial void OnTruong_06Changed();
    partial void OnTruong_07Changing(string value);
    partial void OnTruong_07Changed();
    partial void OnTruong_08Changing(string value);
    partial void OnTruong_08Changed();
    partial void OnTruong_09Changing(string value);
    partial void OnTruong_09Changed();
    partial void OnTruong_10Changing(string value);
    partial void OnTruong_10Changed();
    partial void OnIdPhieuChanging(int value);
    partial void OnIdPhieuChanged();
    partial void OnDemChanging(System.Nullable<int> value);
    partial void OnDemChanged();
    partial void OnErrorChanging(System.Nullable<int> value);
    partial void OnErrorChanged();
    partial void OnTrueChanging(System.Nullable<int> value);
    partial void OnTrueChanged();
    partial void OnDateInputChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInputChanged();
    partial void OnSTTChanging(string value);
    partial void OnSTTChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnLoaiBatchChanging(string value);
    partial void OnLoaiBatchChanged();
    #endregion
		
		public tbl_DESO_Backup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_01", DbType="NVarChar(255)")]
		public string Truong_01
		{
			get
			{
				return this._Truong_01;
			}
			set
			{
				if ((this._Truong_01 != value))
				{
					this.OnTruong_01Changing(value);
					this.SendPropertyChanging();
					this._Truong_01 = value;
					this.SendPropertyChanged("Truong_01");
					this.OnTruong_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_02", DbType="NVarChar(255)")]
		public string Truong_02
		{
			get
			{
				return this._Truong_02;
			}
			set
			{
				if ((this._Truong_02 != value))
				{
					this.OnTruong_02Changing(value);
					this.SendPropertyChanging();
					this._Truong_02 = value;
					this.SendPropertyChanged("Truong_02");
					this.OnTruong_02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_03", DbType="NVarChar(255)")]
		public string Truong_03
		{
			get
			{
				return this._Truong_03;
			}
			set
			{
				if ((this._Truong_03 != value))
				{
					this.OnTruong_03Changing(value);
					this.SendPropertyChanging();
					this._Truong_03 = value;
					this.SendPropertyChanged("Truong_03");
					this.OnTruong_03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_04", DbType="NVarChar(255)")]
		public string Truong_04
		{
			get
			{
				return this._Truong_04;
			}
			set
			{
				if ((this._Truong_04 != value))
				{
					this.OnTruong_04Changing(value);
					this.SendPropertyChanging();
					this._Truong_04 = value;
					this.SendPropertyChanged("Truong_04");
					this.OnTruong_04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_05", DbType="NVarChar(255)")]
		public string Truong_05
		{
			get
			{
				return this._Truong_05;
			}
			set
			{
				if ((this._Truong_05 != value))
				{
					this.OnTruong_05Changing(value);
					this.SendPropertyChanging();
					this._Truong_05 = value;
					this.SendPropertyChanged("Truong_05");
					this.OnTruong_05Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_06", DbType="NVarChar(255)")]
		public string Truong_06
		{
			get
			{
				return this._Truong_06;
			}
			set
			{
				if ((this._Truong_06 != value))
				{
					this.OnTruong_06Changing(value);
					this.SendPropertyChanging();
					this._Truong_06 = value;
					this.SendPropertyChanged("Truong_06");
					this.OnTruong_06Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_07", DbType="NVarChar(255)")]
		public string Truong_07
		{
			get
			{
				return this._Truong_07;
			}
			set
			{
				if ((this._Truong_07 != value))
				{
					this.OnTruong_07Changing(value);
					this.SendPropertyChanging();
					this._Truong_07 = value;
					this.SendPropertyChanged("Truong_07");
					this.OnTruong_07Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_08", DbType="NVarChar(255)")]
		public string Truong_08
		{
			get
			{
				return this._Truong_08;
			}
			set
			{
				if ((this._Truong_08 != value))
				{
					this.OnTruong_08Changing(value);
					this.SendPropertyChanging();
					this._Truong_08 = value;
					this.SendPropertyChanged("Truong_08");
					this.OnTruong_08Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_09", DbType="NVarChar(255)")]
		public string Truong_09
		{
			get
			{
				return this._Truong_09;
			}
			set
			{
				if ((this._Truong_09 != value))
				{
					this.OnTruong_09Changing(value);
					this.SendPropertyChanging();
					this._Truong_09 = value;
					this.SendPropertyChanged("Truong_09");
					this.OnTruong_09Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_10", DbType="NVarChar(255)")]
		public string Truong_10
		{
			get
			{
				return this._Truong_10;
			}
			set
			{
				if ((this._Truong_10 != value))
				{
					this.OnTruong_10Changing(value);
					this.SendPropertyChanging();
					this._Truong_10 = value;
					this.SendPropertyChanged("Truong_10");
					this.OnTruong_10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPhieu
		{
			get
			{
				return this._IdPhieu;
			}
			set
			{
				if ((this._IdPhieu != value))
				{
					this.OnIdPhieuChanging(value);
					this.SendPropertyChanging();
					this._IdPhieu = value;
					this.SendPropertyChanged("IdPhieu");
					this.OnIdPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dem", DbType="Int")]
		public System.Nullable<int> Dem
		{
			get
			{
				return this._Dem;
			}
			set
			{
				if ((this._Dem != value))
				{
					this.OnDemChanging(value);
					this.SendPropertyChanging();
					this._Dem = value;
					this.SendPropertyChanged("Dem");
					this.OnDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Int")]
		public System.Nullable<int> Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_True", DbType="Int")]
		public System.Nullable<int> True
		{
			get
			{
				return this._True;
			}
			set
			{
				if ((this._True != value))
				{
					this.OnTrueChanging(value);
					this.SendPropertyChanging();
					this._True = value;
					this.SendPropertyChanged("True");
					this.OnTrueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInput", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateInput
		{
			get
			{
				return this._DateInput;
			}
			set
			{
				if ((this._DateInput != value))
				{
					this.OnDateInputChanging(value);
					this.SendPropertyChanging();
					this._DateInput = value;
					this.SendPropertyChanged("DateInput");
					this.OnDateInputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="NVarChar(100)")]
		public string STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="NVarChar(255)")]
		public string Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiBatch", DbType="NVarChar(50)")]
		public string LoaiBatch
		{
			get
			{
				return this._LoaiBatch;
			}
			set
			{
				if ((this._LoaiBatch != value))
				{
					this.OnLoaiBatchChanging(value);
					this.SendPropertyChanging();
					this._LoaiBatch = value;
					this.SendPropertyChanged("LoaiBatch");
					this.OnLoaiBatchChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Image")]
	public partial class tbl_Image : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _idimage;
		
		private string _fbatchname;
		
		private string _UserNameDESo;
		
		private int _ReadImageDESo;
		
		private System.Nullable<int> _CheckedDESo;
		
		private string _TienDoDESO;
		
		private System.Nullable<int> _ReadImageDESO_NotGood;
		
		private System.Nullable<int> _ReadImageDESO_Good;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnidimageChanging(string value);
    partial void OnidimageChanged();
    partial void OnfbatchnameChanging(string value);
    partial void OnfbatchnameChanged();
    partial void OnUserNameDESoChanging(string value);
    partial void OnUserNameDESoChanged();
    partial void OnReadImageDESoChanging(int value);
    partial void OnReadImageDESoChanged();
    partial void OnCheckedDESoChanging(System.Nullable<int> value);
    partial void OnCheckedDESoChanged();
    partial void OnTienDoDESOChanging(string value);
    partial void OnTienDoDESOChanged();
    partial void OnReadImageDESO_NotGoodChanging(System.Nullable<int> value);
    partial void OnReadImageDESO_NotGoodChanged();
    partial void OnReadImageDESO_GoodChanging(System.Nullable<int> value);
    partial void OnReadImageDESO_GoodChanged();
    #endregion
		
		public tbl_Image()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idimage", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idimage
		{
			get
			{
				return this._idimage;
			}
			set
			{
				if ((this._idimage != value))
				{
					this.OnidimageChanging(value);
					this.SendPropertyChanging();
					this._idimage = value;
					this.SendPropertyChanged("idimage");
					this.OnidimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fbatchname", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fbatchname
		{
			get
			{
				return this._fbatchname;
			}
			set
			{
				if ((this._fbatchname != value))
				{
					this.OnfbatchnameChanging(value);
					this.SendPropertyChanging();
					this._fbatchname = value;
					this.SendPropertyChanged("fbatchname");
					this.OnfbatchnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNameDESo", DbType="NVarChar(200)")]
		public string UserNameDESo
		{
			get
			{
				return this._UserNameDESo;
			}
			set
			{
				if ((this._UserNameDESo != value))
				{
					this.OnUserNameDESoChanging(value);
					this.SendPropertyChanging();
					this._UserNameDESo = value;
					this.SendPropertyChanged("UserNameDESo");
					this.OnUserNameDESoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadImageDESo", DbType="Int NOT NULL")]
		public int ReadImageDESo
		{
			get
			{
				return this._ReadImageDESo;
			}
			set
			{
				if ((this._ReadImageDESo != value))
				{
					this.OnReadImageDESoChanging(value);
					this.SendPropertyChanging();
					this._ReadImageDESo = value;
					this.SendPropertyChanged("ReadImageDESo");
					this.OnReadImageDESoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckedDESo", DbType="Int")]
		public System.Nullable<int> CheckedDESo
		{
			get
			{
				return this._CheckedDESo;
			}
			set
			{
				if ((this._CheckedDESo != value))
				{
					this.OnCheckedDESoChanging(value);
					this.SendPropertyChanging();
					this._CheckedDESo = value;
					this.SendPropertyChanged("CheckedDESo");
					this.OnCheckedDESoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienDoDESO", DbType="NVarChar(100)")]
		public string TienDoDESO
		{
			get
			{
				return this._TienDoDESO;
			}
			set
			{
				if ((this._TienDoDESO != value))
				{
					this.OnTienDoDESOChanging(value);
					this.SendPropertyChanging();
					this._TienDoDESO = value;
					this.SendPropertyChanged("TienDoDESO");
					this.OnTienDoDESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadImageDESO_NotGood", DbType="Int")]
		public System.Nullable<int> ReadImageDESO_NotGood
		{
			get
			{
				return this._ReadImageDESO_NotGood;
			}
			set
			{
				if ((this._ReadImageDESO_NotGood != value))
				{
					this.OnReadImageDESO_NotGoodChanging(value);
					this.SendPropertyChanging();
					this._ReadImageDESO_NotGood = value;
					this.SendPropertyChanged("ReadImageDESO_NotGood");
					this.OnReadImageDESO_NotGoodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadImageDESO_Good", DbType="Int")]
		public System.Nullable<int> ReadImageDESO_Good
		{
			get
			{
				return this._ReadImageDESO_Good;
			}
			set
			{
				if ((this._ReadImageDESO_Good != value))
				{
					this.OnReadImageDESO_GoodChanging(value);
					this.SendPropertyChanging();
					this._ReadImageDESO_Good = value;
					this.SendPropertyChanged("ReadImageDESO_Good");
					this.OnReadImageDESO_GoodChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_MissCheck_DESO")]
	public partial class tbl_MissCheck_DESO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private System.Nullable<int> _Submit;
		
		private System.Nullable<System.DateTime> _DateCheck;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnSubmitChanging(System.Nullable<int> value);
    partial void OnSubmitChanged();
    partial void OnDateCheckChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCheckChanged();
    #endregion
		
		public tbl_MissCheck_DESO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(255)")]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(255)")]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Submit", DbType="Int")]
		public System.Nullable<int> Submit
		{
			get
			{
				return this._Submit;
			}
			set
			{
				if ((this._Submit != value))
				{
					this.OnSubmitChanging(value);
					this.SendPropertyChanging();
					this._Submit = value;
					this.SendPropertyChanged("Submit");
					this.OnSubmitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCheck", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCheck
		{
			get
			{
				return this._DateCheck;
			}
			set
			{
				if ((this._DateCheck != value))
				{
					this.OnDateCheckChanging(value);
					this.SendPropertyChanging();
					this._DateCheck = value;
					this.SendPropertyChanged("DateCheck");
					this.OnDateCheckChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
