#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natsu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Natsu")]
	public partial class DataNatsuDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_MissImageCheck(tbl_MissImageCheck instance);
    partial void Updatetbl_MissImageCheck(tbl_MissImageCheck instance);
    partial void Deletetbl_MissImageCheck(tbl_MissImageCheck instance);
    partial void Inserttbl_Batch(tbl_Batch instance);
    partial void Updatetbl_Batch(tbl_Batch instance);
    partial void Deletetbl_Batch(tbl_Batch instance);
    partial void Inserttbl_DESo(tbl_DESo instance);
    partial void Updatetbl_DESo(tbl_DESo instance);
    partial void Deletetbl_DESo(tbl_DESo instance);
    partial void Inserttbl_DESo_BackUp(tbl_DESo_BackUp instance);
    partial void Updatetbl_DESo_BackUp(tbl_DESo_BackUp instance);
    partial void Deletetbl_DESo_BackUp(tbl_DESo_BackUp instance);
    partial void Inserttbl_Image(tbl_Image instance);
    partial void Updatetbl_Image(tbl_Image instance);
    partial void Deletetbl_Image(tbl_Image instance);
    partial void Inserttbl_LogFile(tbl_LogFile instance);
    partial void Updatetbl_LogFile(tbl_LogFile instance);
    partial void Deletetbl_LogFile(tbl_LogFile instance);
    partial void Inserttbl_MissImage(tbl_MissImage instance);
    partial void Updatetbl_MissImage(tbl_MissImage instance);
    partial void Deletetbl_MissImage(tbl_MissImage instance);
    #endregion
		
		public DataNatsuDataContext() : 
				base(global::Natsu.Properties.Settings.Default.NatsuConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataNatsuDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataNatsuDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataNatsuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataNatsuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_MissImageCheck> tbl_MissImageChecks
		{
			get
			{
				return this.GetTable<tbl_MissImageCheck>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Batch> tbl_Batches
		{
			get
			{
				return this.GetTable<tbl_Batch>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DESo> tbl_DESos
		{
			get
			{
				return this.GetTable<tbl_DESo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DESo_BackUp> tbl_DESo_BackUps
		{
			get
			{
				return this.GetTable<tbl_DESo_BackUp>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Image> tbl_Images
		{
			get
			{
				return this.GetTable<tbl_Image>();
			}
		}
		
		public System.Data.Linq.Table<tbl_LogFile> tbl_LogFiles
		{
			get
			{
				return this.GetTable<tbl_LogFile>();
			}
		}
		
		public System.Data.Linq.Table<tbl_MissImage> tbl_MissImages
		{
			get
			{
				return this.GetTable<tbl_MissImage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_MissImageCheck")]
	public partial class tbl_MissImageCheck : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserNameCheck;
		
		private int _SubmitCheck;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameCheckChanging(string value);
    partial void OnUserNameCheckChanged();
    partial void OnSubmitCheckChanging(int value);
    partial void OnSubmitCheckChanged();
    #endregion
		
		public tbl_MissImageCheck()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNameCheck", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserNameCheck
		{
			get
			{
				return this._UserNameCheck;
			}
			set
			{
				if ((this._UserNameCheck != value))
				{
					this.OnUserNameCheckChanging(value);
					this.SendPropertyChanging();
					this._UserNameCheck = value;
					this.SendPropertyChanged("UserNameCheck");
					this.OnUserNameCheckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmitCheck", DbType="Int NOT NULL")]
		public int SubmitCheck
		{
			get
			{
				return this._SubmitCheck;
			}
			set
			{
				if ((this._SubmitCheck != value))
				{
					this.OnSubmitCheckChanging(value);
					this.SendPropertyChanging();
					this._SubmitCheck = value;
					this.SendPropertyChanged("SubmitCheck");
					this.OnSubmitCheckChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Batch")]
	public partial class tbl_Batch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDBatch;
		
		private string _fBatchName;
		
		private System.Nullable<System.DateTime> _fdatecreated;
		
		private string _fusercreate;
		
		private string _fPathPicture;
		
		private System.Nullable<bool> _fMultiEntry;
		
		private string _fLocation;
		
		private string _fGhiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBatchChanging(int value);
    partial void OnIDBatchChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnfdatecreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnfdatecreatedChanged();
    partial void OnfusercreateChanging(string value);
    partial void OnfusercreateChanged();
    partial void OnfPathPictureChanging(string value);
    partial void OnfPathPictureChanged();
    partial void OnfMultiEntryChanging(System.Nullable<bool> value);
    partial void OnfMultiEntryChanged();
    partial void OnfLocationChanging(string value);
    partial void OnfLocationChanged();
    partial void OnfGhiChuChanging(string value);
    partial void OnfGhiChuChanged();
    #endregion
		
		public tbl_Batch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBatch", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IDBatch
		{
			get
			{
				return this._IDBatch;
			}
			set
			{
				if ((this._IDBatch != value))
				{
					this.OnIDBatchChanging(value);
					this.SendPropertyChanging();
					this._IDBatch = value;
					this.SendPropertyChanged("IDBatch");
					this.OnIDBatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fdatecreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> fdatecreated
		{
			get
			{
				return this._fdatecreated;
			}
			set
			{
				if ((this._fdatecreated != value))
				{
					this.OnfdatecreatedChanging(value);
					this.SendPropertyChanging();
					this._fdatecreated = value;
					this.SendPropertyChanged("fdatecreated");
					this.OnfdatecreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fusercreate", DbType="NVarChar(200)")]
		public string fusercreate
		{
			get
			{
				return this._fusercreate;
			}
			set
			{
				if ((this._fusercreate != value))
				{
					this.OnfusercreateChanging(value);
					this.SendPropertyChanging();
					this._fusercreate = value;
					this.SendPropertyChanged("fusercreate");
					this.OnfusercreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPathPicture", DbType="NVarChar(200)")]
		public string fPathPicture
		{
			get
			{
				return this._fPathPicture;
			}
			set
			{
				if ((this._fPathPicture != value))
				{
					this.OnfPathPictureChanging(value);
					this.SendPropertyChanging();
					this._fPathPicture = value;
					this.SendPropertyChanged("fPathPicture");
					this.OnfPathPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fMultiEntry", DbType="Bit")]
		public System.Nullable<bool> fMultiEntry
		{
			get
			{
				return this._fMultiEntry;
			}
			set
			{
				if ((this._fMultiEntry != value))
				{
					this.OnfMultiEntryChanging(value);
					this.SendPropertyChanging();
					this._fMultiEntry = value;
					this.SendPropertyChanged("fMultiEntry");
					this.OnfMultiEntryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fLocation", DbType="NVarChar(200)")]
		public string fLocation
		{
			get
			{
				return this._fLocation;
			}
			set
			{
				if ((this._fLocation != value))
				{
					this.OnfLocationChanging(value);
					this.SendPropertyChanging();
					this._fLocation = value;
					this.SendPropertyChanged("fLocation");
					this.OnfLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fGhiChu", DbType="NVarChar(200)")]
		public string fGhiChu
		{
			get
			{
				return this._fGhiChu;
			}
			set
			{
				if ((this._fGhiChu != value))
				{
					this.OnfGhiChuChanging(value);
					this.SendPropertyChanging();
					this._fGhiChu = value;
					this.SendPropertyChanged("fGhiChu");
					this.OnfGhiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DESo")]
	public partial class tbl_DESo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private int _IdPhieu;
		
		private string _TruongSo01;
		
		private string _TruongSo02;
		
		private string _TruongSo03;
		
		private string _TruongSo04;
		
		private string _TruongSo05;
		
		private string _TruongSo06;
		
		private string _TruongSo07;
		
		private string _TruongSo08;
		
		private string _TruongSo09;
		
		private string _TruongSo10;
		
		private string _TruongSo11;
		
		private string _TruongSo12;
		
		private string _TruongSo13;
		
		private string _TruongSo14;
		
		private string _TruongSo15;
		
		private string _TruongSo16;
		
		private string _TruongSo17;
		
		private string _TruongSo18;
		
		private string _TruongSo19;
		
		private string _TruongSo20;
		
		private string _TruongSo21;
		
		private string _TruongSo22;
		
		private string _TruongSo23;
		
		private string _TruongSo24;
		
		private System.Nullable<int> _Dem;
		
		private System.Nullable<int> _Error;
		
		private System.Nullable<int> _True;
		
		private System.Nullable<System.DateTime> _DateInput;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnIdPhieuChanging(int value);
    partial void OnIdPhieuChanged();
    partial void OnTruongSo01Changing(string value);
    partial void OnTruongSo01Changed();
    partial void OnTruongSo02Changing(string value);
    partial void OnTruongSo02Changed();
    partial void OnTruongSo03Changing(string value);
    partial void OnTruongSo03Changed();
    partial void OnTruongSo04Changing(string value);
    partial void OnTruongSo04Changed();
    partial void OnTruongSo05Changing(string value);
    partial void OnTruongSo05Changed();
    partial void OnTruongSo06Changing(string value);
    partial void OnTruongSo06Changed();
    partial void OnTruongSo07Changing(string value);
    partial void OnTruongSo07Changed();
    partial void OnTruongSo08Changing(string value);
    partial void OnTruongSo08Changed();
    partial void OnTruongSo09Changing(string value);
    partial void OnTruongSo09Changed();
    partial void OnTruongSo10Changing(string value);
    partial void OnTruongSo10Changed();
    partial void OnTruongSo11Changing(string value);
    partial void OnTruongSo11Changed();
    partial void OnTruongSo12Changing(string value);
    partial void OnTruongSo12Changed();
    partial void OnTruongSo13Changing(string value);
    partial void OnTruongSo13Changed();
    partial void OnTruongSo14Changing(string value);
    partial void OnTruongSo14Changed();
    partial void OnTruongSo15Changing(string value);
    partial void OnTruongSo15Changed();
    partial void OnTruongSo16Changing(string value);
    partial void OnTruongSo16Changed();
    partial void OnTruongSo17Changing(string value);
    partial void OnTruongSo17Changed();
    partial void OnTruongSo18Changing(string value);
    partial void OnTruongSo18Changed();
    partial void OnTruongSo19Changing(string value);
    partial void OnTruongSo19Changed();
    partial void OnTruongSo20Changing(string value);
    partial void OnTruongSo20Changed();
    partial void OnTruongSo21Changing(string value);
    partial void OnTruongSo21Changed();
    partial void OnTruongSo22Changing(string value);
    partial void OnTruongSo22Changed();
    partial void OnTruongSo23Changing(string value);
    partial void OnTruongSo23Changed();
    partial void OnTruongSo24Changing(string value);
    partial void OnTruongSo24Changed();
    partial void OnDemChanging(System.Nullable<int> value);
    partial void OnDemChanged();
    partial void OnErrorChanging(System.Nullable<int> value);
    partial void OnErrorChanged();
    partial void OnTrueChanging(System.Nullable<int> value);
    partial void OnTrueChanged();
    partial void OnDateInputChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInputChanged();
    #endregion
		
		public tbl_DESo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPhieu
		{
			get
			{
				return this._IdPhieu;
			}
			set
			{
				if ((this._IdPhieu != value))
				{
					this.OnIdPhieuChanging(value);
					this.SendPropertyChanging();
					this._IdPhieu = value;
					this.SendPropertyChanged("IdPhieu");
					this.OnIdPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo01", DbType="NVarChar(100)")]
		public string TruongSo01
		{
			get
			{
				return this._TruongSo01;
			}
			set
			{
				if ((this._TruongSo01 != value))
				{
					this.OnTruongSo01Changing(value);
					this.SendPropertyChanging();
					this._TruongSo01 = value;
					this.SendPropertyChanged("TruongSo01");
					this.OnTruongSo01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo02", DbType="NVarChar(100)")]
		public string TruongSo02
		{
			get
			{
				return this._TruongSo02;
			}
			set
			{
				if ((this._TruongSo02 != value))
				{
					this.OnTruongSo02Changing(value);
					this.SendPropertyChanging();
					this._TruongSo02 = value;
					this.SendPropertyChanged("TruongSo02");
					this.OnTruongSo02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo03", DbType="NVarChar(100)")]
		public string TruongSo03
		{
			get
			{
				return this._TruongSo03;
			}
			set
			{
				if ((this._TruongSo03 != value))
				{
					this.OnTruongSo03Changing(value);
					this.SendPropertyChanging();
					this._TruongSo03 = value;
					this.SendPropertyChanged("TruongSo03");
					this.OnTruongSo03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo04", DbType="NVarChar(100)")]
		public string TruongSo04
		{
			get
			{
				return this._TruongSo04;
			}
			set
			{
				if ((this._TruongSo04 != value))
				{
					this.OnTruongSo04Changing(value);
					this.SendPropertyChanging();
					this._TruongSo04 = value;
					this.SendPropertyChanged("TruongSo04");
					this.OnTruongSo04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo05", DbType="NVarChar(100)")]
		public string TruongSo05
		{
			get
			{
				return this._TruongSo05;
			}
			set
			{
				if ((this._TruongSo05 != value))
				{
					this.OnTruongSo05Changing(value);
					this.SendPropertyChanging();
					this._TruongSo05 = value;
					this.SendPropertyChanged("TruongSo05");
					this.OnTruongSo05Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo06", DbType="NVarChar(100)")]
		public string TruongSo06
		{
			get
			{
				return this._TruongSo06;
			}
			set
			{
				if ((this._TruongSo06 != value))
				{
					this.OnTruongSo06Changing(value);
					this.SendPropertyChanging();
					this._TruongSo06 = value;
					this.SendPropertyChanged("TruongSo06");
					this.OnTruongSo06Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo07", DbType="NVarChar(100)")]
		public string TruongSo07
		{
			get
			{
				return this._TruongSo07;
			}
			set
			{
				if ((this._TruongSo07 != value))
				{
					this.OnTruongSo07Changing(value);
					this.SendPropertyChanging();
					this._TruongSo07 = value;
					this.SendPropertyChanged("TruongSo07");
					this.OnTruongSo07Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo08", DbType="NVarChar(100)")]
		public string TruongSo08
		{
			get
			{
				return this._TruongSo08;
			}
			set
			{
				if ((this._TruongSo08 != value))
				{
					this.OnTruongSo08Changing(value);
					this.SendPropertyChanging();
					this._TruongSo08 = value;
					this.SendPropertyChanged("TruongSo08");
					this.OnTruongSo08Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo09", DbType="NVarChar(100)")]
		public string TruongSo09
		{
			get
			{
				return this._TruongSo09;
			}
			set
			{
				if ((this._TruongSo09 != value))
				{
					this.OnTruongSo09Changing(value);
					this.SendPropertyChanging();
					this._TruongSo09 = value;
					this.SendPropertyChanged("TruongSo09");
					this.OnTruongSo09Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo10", DbType="NVarChar(100)")]
		public string TruongSo10
		{
			get
			{
				return this._TruongSo10;
			}
			set
			{
				if ((this._TruongSo10 != value))
				{
					this.OnTruongSo10Changing(value);
					this.SendPropertyChanging();
					this._TruongSo10 = value;
					this.SendPropertyChanged("TruongSo10");
					this.OnTruongSo10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo11", DbType="NVarChar(100)")]
		public string TruongSo11
		{
			get
			{
				return this._TruongSo11;
			}
			set
			{
				if ((this._TruongSo11 != value))
				{
					this.OnTruongSo11Changing(value);
					this.SendPropertyChanging();
					this._TruongSo11 = value;
					this.SendPropertyChanged("TruongSo11");
					this.OnTruongSo11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo12", DbType="NVarChar(100)")]
		public string TruongSo12
		{
			get
			{
				return this._TruongSo12;
			}
			set
			{
				if ((this._TruongSo12 != value))
				{
					this.OnTruongSo12Changing(value);
					this.SendPropertyChanging();
					this._TruongSo12 = value;
					this.SendPropertyChanged("TruongSo12");
					this.OnTruongSo12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo13", DbType="NVarChar(100)")]
		public string TruongSo13
		{
			get
			{
				return this._TruongSo13;
			}
			set
			{
				if ((this._TruongSo13 != value))
				{
					this.OnTruongSo13Changing(value);
					this.SendPropertyChanging();
					this._TruongSo13 = value;
					this.SendPropertyChanged("TruongSo13");
					this.OnTruongSo13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo14", DbType="NVarChar(100)")]
		public string TruongSo14
		{
			get
			{
				return this._TruongSo14;
			}
			set
			{
				if ((this._TruongSo14 != value))
				{
					this.OnTruongSo14Changing(value);
					this.SendPropertyChanging();
					this._TruongSo14 = value;
					this.SendPropertyChanged("TruongSo14");
					this.OnTruongSo14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo15", DbType="NVarChar(100)")]
		public string TruongSo15
		{
			get
			{
				return this._TruongSo15;
			}
			set
			{
				if ((this._TruongSo15 != value))
				{
					this.OnTruongSo15Changing(value);
					this.SendPropertyChanging();
					this._TruongSo15 = value;
					this.SendPropertyChanged("TruongSo15");
					this.OnTruongSo15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo16", DbType="NVarChar(100)")]
		public string TruongSo16
		{
			get
			{
				return this._TruongSo16;
			}
			set
			{
				if ((this._TruongSo16 != value))
				{
					this.OnTruongSo16Changing(value);
					this.SendPropertyChanging();
					this._TruongSo16 = value;
					this.SendPropertyChanged("TruongSo16");
					this.OnTruongSo16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo17", DbType="NVarChar(100)")]
		public string TruongSo17
		{
			get
			{
				return this._TruongSo17;
			}
			set
			{
				if ((this._TruongSo17 != value))
				{
					this.OnTruongSo17Changing(value);
					this.SendPropertyChanging();
					this._TruongSo17 = value;
					this.SendPropertyChanged("TruongSo17");
					this.OnTruongSo17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo18", DbType="NVarChar(100)")]
		public string TruongSo18
		{
			get
			{
				return this._TruongSo18;
			}
			set
			{
				if ((this._TruongSo18 != value))
				{
					this.OnTruongSo18Changing(value);
					this.SendPropertyChanging();
					this._TruongSo18 = value;
					this.SendPropertyChanged("TruongSo18");
					this.OnTruongSo18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo19", DbType="NVarChar(100)")]
		public string TruongSo19
		{
			get
			{
				return this._TruongSo19;
			}
			set
			{
				if ((this._TruongSo19 != value))
				{
					this.OnTruongSo19Changing(value);
					this.SendPropertyChanging();
					this._TruongSo19 = value;
					this.SendPropertyChanged("TruongSo19");
					this.OnTruongSo19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo20", DbType="NVarChar(100)")]
		public string TruongSo20
		{
			get
			{
				return this._TruongSo20;
			}
			set
			{
				if ((this._TruongSo20 != value))
				{
					this.OnTruongSo20Changing(value);
					this.SendPropertyChanging();
					this._TruongSo20 = value;
					this.SendPropertyChanged("TruongSo20");
					this.OnTruongSo20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo21", DbType="NVarChar(100)")]
		public string TruongSo21
		{
			get
			{
				return this._TruongSo21;
			}
			set
			{
				if ((this._TruongSo21 != value))
				{
					this.OnTruongSo21Changing(value);
					this.SendPropertyChanging();
					this._TruongSo21 = value;
					this.SendPropertyChanged("TruongSo21");
					this.OnTruongSo21Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo22", DbType="NVarChar(100)")]
		public string TruongSo22
		{
			get
			{
				return this._TruongSo22;
			}
			set
			{
				if ((this._TruongSo22 != value))
				{
					this.OnTruongSo22Changing(value);
					this.SendPropertyChanging();
					this._TruongSo22 = value;
					this.SendPropertyChanged("TruongSo22");
					this.OnTruongSo22Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo23", DbType="NVarChar(100)")]
		public string TruongSo23
		{
			get
			{
				return this._TruongSo23;
			}
			set
			{
				if ((this._TruongSo23 != value))
				{
					this.OnTruongSo23Changing(value);
					this.SendPropertyChanging();
					this._TruongSo23 = value;
					this.SendPropertyChanged("TruongSo23");
					this.OnTruongSo23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo24", DbType="NVarChar(100)")]
		public string TruongSo24
		{
			get
			{
				return this._TruongSo24;
			}
			set
			{
				if ((this._TruongSo24 != value))
				{
					this.OnTruongSo24Changing(value);
					this.SendPropertyChanging();
					this._TruongSo24 = value;
					this.SendPropertyChanged("TruongSo24");
					this.OnTruongSo24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dem", DbType="Int")]
		public System.Nullable<int> Dem
		{
			get
			{
				return this._Dem;
			}
			set
			{
				if ((this._Dem != value))
				{
					this.OnDemChanging(value);
					this.SendPropertyChanging();
					this._Dem = value;
					this.SendPropertyChanged("Dem");
					this.OnDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Int")]
		public System.Nullable<int> Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_True", DbType="Int")]
		public System.Nullable<int> True
		{
			get
			{
				return this._True;
			}
			set
			{
				if ((this._True != value))
				{
					this.OnTrueChanging(value);
					this.SendPropertyChanging();
					this._True = value;
					this.SendPropertyChanged("True");
					this.OnTrueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInput", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateInput
		{
			get
			{
				return this._DateInput;
			}
			set
			{
				if ((this._DateInput != value))
				{
					this.OnDateInputChanging(value);
					this.SendPropertyChanging();
					this._DateInput = value;
					this.SendPropertyChanged("DateInput");
					this.OnDateInputChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DESo_BackUp")]
	public partial class tbl_DESo_BackUp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private int _IdPhieu;
		
		private string _TruongSo01;
		
		private string _TruongSo02;
		
		private string _TruongSo03;
		
		private string _TruongSo04;
		
		private string _TruongSo05;
		
		private string _TruongSo06;
		
		private string _TruongSo07;
		
		private string _TruongSo08;
		
		private string _TruongSo09;
		
		private string _TruongSo10;
		
		private string _TruongSo11;
		
		private string _TruongSo12;
		
		private string _TruongSo13;
		
		private string _TruongSo14;
		
		private string _TruongSo15;
		
		private string _TruongSo16;
		
		private string _TruongSo17;
		
		private string _TruongSo18;
		
		private string _TruongSo19;
		
		private string _TruongSo20;
		
		private string _TruongSo21;
		
		private string _TruongSo22;
		
		private string _TruongSo23;
		
		private string _TruongSo24;
		
		private System.Nullable<int> _Dem;
		
		private System.Nullable<int> _Error;
		
		private System.Nullable<int> _True;
		
		private System.Nullable<System.DateTime> _DateInput;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnIdPhieuChanging(int value);
    partial void OnIdPhieuChanged();
    partial void OnTruongSo01Changing(string value);
    partial void OnTruongSo01Changed();
    partial void OnTruongSo02Changing(string value);
    partial void OnTruongSo02Changed();
    partial void OnTruongSo03Changing(string value);
    partial void OnTruongSo03Changed();
    partial void OnTruongSo04Changing(string value);
    partial void OnTruongSo04Changed();
    partial void OnTruongSo05Changing(string value);
    partial void OnTruongSo05Changed();
    partial void OnTruongSo06Changing(string value);
    partial void OnTruongSo06Changed();
    partial void OnTruongSo07Changing(string value);
    partial void OnTruongSo07Changed();
    partial void OnTruongSo08Changing(string value);
    partial void OnTruongSo08Changed();
    partial void OnTruongSo09Changing(string value);
    partial void OnTruongSo09Changed();
    partial void OnTruongSo10Changing(string value);
    partial void OnTruongSo10Changed();
    partial void OnTruongSo11Changing(string value);
    partial void OnTruongSo11Changed();
    partial void OnTruongSo12Changing(string value);
    partial void OnTruongSo12Changed();
    partial void OnTruongSo13Changing(string value);
    partial void OnTruongSo13Changed();
    partial void OnTruongSo14Changing(string value);
    partial void OnTruongSo14Changed();
    partial void OnTruongSo15Changing(string value);
    partial void OnTruongSo15Changed();
    partial void OnTruongSo16Changing(string value);
    partial void OnTruongSo16Changed();
    partial void OnTruongSo17Changing(string value);
    partial void OnTruongSo17Changed();
    partial void OnTruongSo18Changing(string value);
    partial void OnTruongSo18Changed();
    partial void OnTruongSo19Changing(string value);
    partial void OnTruongSo19Changed();
    partial void OnTruongSo20Changing(string value);
    partial void OnTruongSo20Changed();
    partial void OnTruongSo21Changing(string value);
    partial void OnTruongSo21Changed();
    partial void OnTruongSo22Changing(string value);
    partial void OnTruongSo22Changed();
    partial void OnTruongSo23Changing(string value);
    partial void OnTruongSo23Changed();
    partial void OnTruongSo24Changing(string value);
    partial void OnTruongSo24Changed();
    partial void OnDemChanging(System.Nullable<int> value);
    partial void OnDemChanged();
    partial void OnErrorChanging(System.Nullable<int> value);
    partial void OnErrorChanged();
    partial void OnTrueChanging(System.Nullable<int> value);
    partial void OnTrueChanged();
    partial void OnDateInputChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInputChanged();
    #endregion
		
		public tbl_DESo_BackUp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPhieu
		{
			get
			{
				return this._IdPhieu;
			}
			set
			{
				if ((this._IdPhieu != value))
				{
					this.OnIdPhieuChanging(value);
					this.SendPropertyChanging();
					this._IdPhieu = value;
					this.SendPropertyChanged("IdPhieu");
					this.OnIdPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo01", DbType="NVarChar(100)")]
		public string TruongSo01
		{
			get
			{
				return this._TruongSo01;
			}
			set
			{
				if ((this._TruongSo01 != value))
				{
					this.OnTruongSo01Changing(value);
					this.SendPropertyChanging();
					this._TruongSo01 = value;
					this.SendPropertyChanged("TruongSo01");
					this.OnTruongSo01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo02", DbType="NVarChar(100)")]
		public string TruongSo02
		{
			get
			{
				return this._TruongSo02;
			}
			set
			{
				if ((this._TruongSo02 != value))
				{
					this.OnTruongSo02Changing(value);
					this.SendPropertyChanging();
					this._TruongSo02 = value;
					this.SendPropertyChanged("TruongSo02");
					this.OnTruongSo02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo03", DbType="NVarChar(100)")]
		public string TruongSo03
		{
			get
			{
				return this._TruongSo03;
			}
			set
			{
				if ((this._TruongSo03 != value))
				{
					this.OnTruongSo03Changing(value);
					this.SendPropertyChanging();
					this._TruongSo03 = value;
					this.SendPropertyChanged("TruongSo03");
					this.OnTruongSo03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo04", DbType="NVarChar(100)")]
		public string TruongSo04
		{
			get
			{
				return this._TruongSo04;
			}
			set
			{
				if ((this._TruongSo04 != value))
				{
					this.OnTruongSo04Changing(value);
					this.SendPropertyChanging();
					this._TruongSo04 = value;
					this.SendPropertyChanged("TruongSo04");
					this.OnTruongSo04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo05", DbType="NVarChar(100)")]
		public string TruongSo05
		{
			get
			{
				return this._TruongSo05;
			}
			set
			{
				if ((this._TruongSo05 != value))
				{
					this.OnTruongSo05Changing(value);
					this.SendPropertyChanging();
					this._TruongSo05 = value;
					this.SendPropertyChanged("TruongSo05");
					this.OnTruongSo05Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo06", DbType="NVarChar(100)")]
		public string TruongSo06
		{
			get
			{
				return this._TruongSo06;
			}
			set
			{
				if ((this._TruongSo06 != value))
				{
					this.OnTruongSo06Changing(value);
					this.SendPropertyChanging();
					this._TruongSo06 = value;
					this.SendPropertyChanged("TruongSo06");
					this.OnTruongSo06Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo07", DbType="NVarChar(100)")]
		public string TruongSo07
		{
			get
			{
				return this._TruongSo07;
			}
			set
			{
				if ((this._TruongSo07 != value))
				{
					this.OnTruongSo07Changing(value);
					this.SendPropertyChanging();
					this._TruongSo07 = value;
					this.SendPropertyChanged("TruongSo07");
					this.OnTruongSo07Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo08", DbType="NVarChar(100)")]
		public string TruongSo08
		{
			get
			{
				return this._TruongSo08;
			}
			set
			{
				if ((this._TruongSo08 != value))
				{
					this.OnTruongSo08Changing(value);
					this.SendPropertyChanging();
					this._TruongSo08 = value;
					this.SendPropertyChanged("TruongSo08");
					this.OnTruongSo08Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo09", DbType="NVarChar(100)")]
		public string TruongSo09
		{
			get
			{
				return this._TruongSo09;
			}
			set
			{
				if ((this._TruongSo09 != value))
				{
					this.OnTruongSo09Changing(value);
					this.SendPropertyChanging();
					this._TruongSo09 = value;
					this.SendPropertyChanged("TruongSo09");
					this.OnTruongSo09Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo10", DbType="NVarChar(100)")]
		public string TruongSo10
		{
			get
			{
				return this._TruongSo10;
			}
			set
			{
				if ((this._TruongSo10 != value))
				{
					this.OnTruongSo10Changing(value);
					this.SendPropertyChanging();
					this._TruongSo10 = value;
					this.SendPropertyChanged("TruongSo10");
					this.OnTruongSo10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo11", DbType="NVarChar(100)")]
		public string TruongSo11
		{
			get
			{
				return this._TruongSo11;
			}
			set
			{
				if ((this._TruongSo11 != value))
				{
					this.OnTruongSo11Changing(value);
					this.SendPropertyChanging();
					this._TruongSo11 = value;
					this.SendPropertyChanged("TruongSo11");
					this.OnTruongSo11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo12", DbType="NVarChar(100)")]
		public string TruongSo12
		{
			get
			{
				return this._TruongSo12;
			}
			set
			{
				if ((this._TruongSo12 != value))
				{
					this.OnTruongSo12Changing(value);
					this.SendPropertyChanging();
					this._TruongSo12 = value;
					this.SendPropertyChanged("TruongSo12");
					this.OnTruongSo12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo13", DbType="NVarChar(100)")]
		public string TruongSo13
		{
			get
			{
				return this._TruongSo13;
			}
			set
			{
				if ((this._TruongSo13 != value))
				{
					this.OnTruongSo13Changing(value);
					this.SendPropertyChanging();
					this._TruongSo13 = value;
					this.SendPropertyChanged("TruongSo13");
					this.OnTruongSo13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo14", DbType="NVarChar(100)")]
		public string TruongSo14
		{
			get
			{
				return this._TruongSo14;
			}
			set
			{
				if ((this._TruongSo14 != value))
				{
					this.OnTruongSo14Changing(value);
					this.SendPropertyChanging();
					this._TruongSo14 = value;
					this.SendPropertyChanged("TruongSo14");
					this.OnTruongSo14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo15", DbType="NVarChar(100)")]
		public string TruongSo15
		{
			get
			{
				return this._TruongSo15;
			}
			set
			{
				if ((this._TruongSo15 != value))
				{
					this.OnTruongSo15Changing(value);
					this.SendPropertyChanging();
					this._TruongSo15 = value;
					this.SendPropertyChanged("TruongSo15");
					this.OnTruongSo15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo16", DbType="NVarChar(100)")]
		public string TruongSo16
		{
			get
			{
				return this._TruongSo16;
			}
			set
			{
				if ((this._TruongSo16 != value))
				{
					this.OnTruongSo16Changing(value);
					this.SendPropertyChanging();
					this._TruongSo16 = value;
					this.SendPropertyChanged("TruongSo16");
					this.OnTruongSo16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo17", DbType="NVarChar(100)")]
		public string TruongSo17
		{
			get
			{
				return this._TruongSo17;
			}
			set
			{
				if ((this._TruongSo17 != value))
				{
					this.OnTruongSo17Changing(value);
					this.SendPropertyChanging();
					this._TruongSo17 = value;
					this.SendPropertyChanged("TruongSo17");
					this.OnTruongSo17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo18", DbType="NVarChar(100)")]
		public string TruongSo18
		{
			get
			{
				return this._TruongSo18;
			}
			set
			{
				if ((this._TruongSo18 != value))
				{
					this.OnTruongSo18Changing(value);
					this.SendPropertyChanging();
					this._TruongSo18 = value;
					this.SendPropertyChanged("TruongSo18");
					this.OnTruongSo18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo19", DbType="NVarChar(100)")]
		public string TruongSo19
		{
			get
			{
				return this._TruongSo19;
			}
			set
			{
				if ((this._TruongSo19 != value))
				{
					this.OnTruongSo19Changing(value);
					this.SendPropertyChanging();
					this._TruongSo19 = value;
					this.SendPropertyChanged("TruongSo19");
					this.OnTruongSo19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo20", DbType="NVarChar(100)")]
		public string TruongSo20
		{
			get
			{
				return this._TruongSo20;
			}
			set
			{
				if ((this._TruongSo20 != value))
				{
					this.OnTruongSo20Changing(value);
					this.SendPropertyChanging();
					this._TruongSo20 = value;
					this.SendPropertyChanged("TruongSo20");
					this.OnTruongSo20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo21", DbType="NVarChar(100)")]
		public string TruongSo21
		{
			get
			{
				return this._TruongSo21;
			}
			set
			{
				if ((this._TruongSo21 != value))
				{
					this.OnTruongSo21Changing(value);
					this.SendPropertyChanging();
					this._TruongSo21 = value;
					this.SendPropertyChanged("TruongSo21");
					this.OnTruongSo21Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo22", DbType="NVarChar(100)")]
		public string TruongSo22
		{
			get
			{
				return this._TruongSo22;
			}
			set
			{
				if ((this._TruongSo22 != value))
				{
					this.OnTruongSo22Changing(value);
					this.SendPropertyChanging();
					this._TruongSo22 = value;
					this.SendPropertyChanged("TruongSo22");
					this.OnTruongSo22Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo23", DbType="NVarChar(100)")]
		public string TruongSo23
		{
			get
			{
				return this._TruongSo23;
			}
			set
			{
				if ((this._TruongSo23 != value))
				{
					this.OnTruongSo23Changing(value);
					this.SendPropertyChanging();
					this._TruongSo23 = value;
					this.SendPropertyChanged("TruongSo23");
					this.OnTruongSo23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongSo24", DbType="NVarChar(100)")]
		public string TruongSo24
		{
			get
			{
				return this._TruongSo24;
			}
			set
			{
				if ((this._TruongSo24 != value))
				{
					this.OnTruongSo24Changing(value);
					this.SendPropertyChanging();
					this._TruongSo24 = value;
					this.SendPropertyChanged("TruongSo24");
					this.OnTruongSo24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dem", DbType="Int")]
		public System.Nullable<int> Dem
		{
			get
			{
				return this._Dem;
			}
			set
			{
				if ((this._Dem != value))
				{
					this.OnDemChanging(value);
					this.SendPropertyChanging();
					this._Dem = value;
					this.SendPropertyChanged("Dem");
					this.OnDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Int")]
		public System.Nullable<int> Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_True", DbType="Int")]
		public System.Nullable<int> True
		{
			get
			{
				return this._True;
			}
			set
			{
				if ((this._True != value))
				{
					this.OnTrueChanging(value);
					this.SendPropertyChanging();
					this._True = value;
					this.SendPropertyChanged("True");
					this.OnTrueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInput", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateInput
		{
			get
			{
				return this._DateInput;
			}
			set
			{
				if ((this._DateInput != value))
				{
					this.OnDateInputChanging(value);
					this.SendPropertyChanging();
					this._DateInput = value;
					this.SendPropertyChanged("DateInput");
					this.OnDateInputChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Image")]
	public partial class tbl_Image : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserNameDESo;
		
		private int _ReadImageDESo;
		
		private System.Nullable<int> _CheckedDESo;
		
		private string _TienDoDESO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameDESoChanging(string value);
    partial void OnUserNameDESoChanged();
    partial void OnReadImageDESoChanging(int value);
    partial void OnReadImageDESoChanged();
    partial void OnCheckedDESoChanging(System.Nullable<int> value);
    partial void OnCheckedDESoChanged();
    partial void OnTienDoDESOChanging(string value);
    partial void OnTienDoDESOChanged();
    #endregion
		
		public tbl_Image()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNameDESo", DbType="NVarChar(100)")]
		public string UserNameDESo
		{
			get
			{
				return this._UserNameDESo;
			}
			set
			{
				if ((this._UserNameDESo != value))
				{
					this.OnUserNameDESoChanging(value);
					this.SendPropertyChanging();
					this._UserNameDESo = value;
					this.SendPropertyChanged("UserNameDESo");
					this.OnUserNameDESoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadImageDESo", DbType="Int NOT NULL")]
		public int ReadImageDESo
		{
			get
			{
				return this._ReadImageDESo;
			}
			set
			{
				if ((this._ReadImageDESo != value))
				{
					this.OnReadImageDESoChanging(value);
					this.SendPropertyChanging();
					this._ReadImageDESo = value;
					this.SendPropertyChanged("ReadImageDESo");
					this.OnReadImageDESoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckedDESo", DbType="Int")]
		public System.Nullable<int> CheckedDESo
		{
			get
			{
				return this._CheckedDESo;
			}
			set
			{
				if ((this._CheckedDESo != value))
				{
					this.OnCheckedDESoChanging(value);
					this.SendPropertyChanging();
					this._CheckedDESo = value;
					this.SendPropertyChanged("CheckedDESo");
					this.OnCheckedDESoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienDoDESO", DbType="NVarChar(100)")]
		public string TienDoDESO
		{
			get
			{
				return this._TienDoDESO;
			}
			set
			{
				if ((this._TienDoDESO != value))
				{
					this.OnTienDoDESOChanging(value);
					this.SendPropertyChanging();
					this._TienDoDESO = value;
					this.SendPropertyChanged("TienDoDESO");
					this.OnTienDoDESOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_LogFile")]
	public partial class tbl_LogFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Username;
		
		private string _Info;
		
		private System.Nullable<System.DateTime> _DateLog;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnInfoChanging(string value);
    partial void OnInfoChanged();
    partial void OnDateLogChanging(System.Nullable<System.DateTime> value);
    partial void OnDateLogChanged();
    #endregion
		
		public tbl_LogFile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(200)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Info", DbType="NVarChar(2000)")]
		public string Info
		{
			get
			{
				return this._Info;
			}
			set
			{
				if ((this._Info != value))
				{
					this.OnInfoChanging(value);
					this.SendPropertyChanging();
					this._Info = value;
					this.SendPropertyChanged("Info");
					this.OnInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLog", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateLog
		{
			get
			{
				return this._DateLog;
			}
			set
			{
				if ((this._DateLog != value))
				{
					this.OnDateLogChanging(value);
					this.SendPropertyChanging();
					this._DateLog = value;
					this.SendPropertyChanged("DateLog");
					this.OnDateLogChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_MissImage")]
	public partial class tbl_MissImage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserNameDESo;
		
		private System.Nullable<int> _SubmitDESo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameDESoChanging(string value);
    partial void OnUserNameDESoChanged();
    partial void OnSubmitDESoChanging(System.Nullable<int> value);
    partial void OnSubmitDESoChanged();
    #endregion
		
		public tbl_MissImage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNameDESo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserNameDESo
		{
			get
			{
				return this._UserNameDESo;
			}
			set
			{
				if ((this._UserNameDESo != value))
				{
					this.OnUserNameDESoChanging(value);
					this.SendPropertyChanging();
					this._UserNameDESo = value;
					this.SendPropertyChanged("UserNameDESo");
					this.OnUserNameDESoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmitDESo", DbType="Int")]
		public System.Nullable<int> SubmitDESo
		{
			get
			{
				return this._SubmitDESo;
			}
			set
			{
				if ((this._SubmitDESo != value))
				{
					this.OnSubmitDESoChanging(value);
					this.SendPropertyChanging();
					this._SubmitDESo = value;
					this.SendPropertyChanged("SubmitDESo");
					this.OnSubmitDESoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
